Rename function pointers to avoid shadowing global declaration
BoringSSL compilation with -Wshadow fails with following error

error: declaration of 'write' shadows a global declaration [-Werror=shadow]
  673 |                        int (*write)(BIO *, const char *, int)) {
      |                        ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Renamed function pointers to fix this error.

Bug: b:321092852
Change-Id: I94f988e5c12da5eae93f16e6666bc7ab5ca0fc06
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/68107
Commit-Queue: David Benjamin <davidben@google.com>
Reviewed-by: Bob Beck <bbe@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
(cherry picked from commit 70d05d5a34f6366116e2b0a530ea8d0186bb2a8e)
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@surgut.co.uk>