Fix pointers in CONSTTIME_DECLASSIFY.
Tested by compiling with valgrind.

Before:
$ cmake -GNinja -B build -D CONSTANT_TIME_VALIDATION=1
$ ninja -C build
[...]
/home/tholenst/boringssl/boringssl/crypto/dilithium/dilithium.c:1199:25: error: ‘pub’ undeclared (first use in this function)
 1199 |   CONSTTIME_DECLASSIFY(&pub.t1, sizeof(pub.t1));

After:

$ ninja -C build
ninja: Entering directory `build'
[440/440] Linking CXX executable ssl/test/handshaker

Change-Id: I26481d69e9d033b0c23b7486970991b673132d20
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/69267
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: David Benjamin <davidben@google.com>
(cherry picked from commit 9cac8a6b38c1cbd45c77aee108411d588da006fe)
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@surgut.co.uk>