Include <string> in pki/string_util.h
This is necessary to avoid the following error when building with MSVC
using the latest STL:

    error C2039: 'string': is not a member of 'std'

Change-Id: I4c926f7a020c2e920bcc78667bc04951cdab4cf1
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/70272
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: David Benjamin <davidben@google.com>
(cherry picked from commit 12391e648d3c6f04a718721568cc89208b780654)
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@surgut.co.uk>